{{- if .Values.prometheusCollector.enabled }}
{{- $tlsEnabled := .Values.prometheusCollector.tls.enabled }}
{{- $basicAuthEnabled := .Values.prometheusCollector.basicAuth.enabled }}
{{- if or $tlsEnabled $basicAuthEnabled }}
{{- $cert := genSelfSignedCert "prometheus-collector" nil (list "localhost" (printf "%s-prometheus-collector" (include "pgdog.fullname" .))) 3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgdog.fullname" . }}-prometheus-collector
  labels:
    {{- include "pgdog.prometheusCollector.labels" . | nindent 4 }}
type: Opaque
stringData:
  web.yml: |
    {{- if $tlsEnabled }}
    tls_server_config:
      cert_file: /etc/prometheus-web/tls.crt
      key_file: /etc/prometheus-web/tls.key
    {{- end }}
    {{- if $basicAuthEnabled }}
    basic_auth_users:
      {{ .Values.prometheusCollector.basicAuth.username }}: {{ .Values.prometheusCollector.basicAuth.passwordHash }}
    {{- end }}
  {{- if $basicAuthEnabled }}
  password: {{ .Values.prometheusCollector.basicAuth.password | quote }}
  {{- end }}
  {{- if $tlsEnabled }}
  tls.crt: |
{{ $cert.Cert | indent 4 }}
  tls.key: |
{{ $cert.Key | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
