{{- if and .Values.prometheusCollector.enabled .Values.prometheusCollector.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgdog.fullname" . }}-prometheus-collector
  labels:
    {{- include "pgdog.prometheusCollector.labels" . | nindent 4 }}
type: Opaque
stringData:
  web.yml: |
    basic_auth_users:
      {{ .Values.prometheusCollector.basicAuth.username }}: {{ .Values.prometheusCollector.basicAuth.passwordHash }}
{{- end }}
